In [3]:
import numpy as num    #i
L=num.arange(0,16)
print(L)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [4]:
L=num.chararray(3,3)
print(L)

[b'll' b'val' b'ues']


In [ ]:
print(L.dtype)

int64


In [ ]:
A=num.zeros(10)
B=A.astype(int)
print(B.dtype)
print(B)

int64
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
B=num.ones(30).reshape((5,6))
print(B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#Create 4X4 matrix where each of the values are 2.12. 
                                #ALT METHOD
                                #C=num.zeros((4,4))
                                #[::][::]=2.12
C=num.full((4,4),2.12)
print(C)

[[2.12 2.12 2.12 2.12]
 [2.12 2.12 2.12 2.12]
 [2.12 2.12 2.12 2.12]
 [2.12 2.12 2.12 2.12]]


In [ ]:
#Create an array of integers from multiples of 3 below 30.

D=num.arange(3,31,3)
print(D)
print(D.dtype)

[ 3  6  9 12 15 18 21 24 27 30]
int64


In [ ]:
#Create an array of ten numbers starting from 1 to 5 and the numbers must be having equal difference. Example 10, 1.5, 2.0, 2.5 ...... 

E=num.linspace(1,5,10)
print(E)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
#Create a 3X3 array of random numbers with mean 0 and standard deviation as 1. 
my_mean=0
my_std=1
x = num.random.normal(loc=my_mean, scale=my_std, size=9)
y=num.reshape(x,(3,3))
print(y)

[[ 0.22222482 -0.20172725  1.76025542]
 [ 0.08371127 -0.31348231  0.26986506]
 [ 0.91777963 -0.93424826 -1.08599926]]


In [ ]:
#Create and identity matrix of dimension 5X5

P=num.identity(5,dtype="f")
print(P)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
'''Create an array of integers from 0 to 19 and print the values.
 And use this array for answering the following questions
 a.Print first five elements.
 b.Print last five elements.c.
 Print element from 4thposition to last.
 d.Print the elements at even places.
  e.Print elements from first position step by three
  f.Print the array in reverse order.'''

c=num.arange(0,20)
print(c)
print(c[:5])
print(c[15:])
print(c[-4])

print(num.flip(L))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4]
[15 16 17 18 19]
16


In [ ]:
#Create arrays X, Y, Z with the following data.
#X = 1,2,3,4,5
#Y=10, 20, 30, 40, 50
#Z =100, 200, 300, 400, 500
X=num.array([1,2,3,4,5])
print("X:", X) 
Y=num.array([10,20,30,40,50])
print("Y:", Y)
Z=num.array([100,200,300,400,500])
print("Z:", Z)

X: [1 2 3 4 5]
Y: [10 20 30 40 50]
Z: [100 200 300 400 500]


In [ ]:
N=num.arange(0,20).reshape((4,5))
print(N)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
